server:
  port: 19003
  servlet:
    context-path: /moreDataSource

#spring cache caffeine settings
spring:
  application:
    name: springboot-more-datasource
  main:
    allow-bean-definition-overriding: true

    # 数据源配置
  datasource:
    # 驱动类名，这里使用的是ShardingSphere提供的驱动
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 数据源URL，使用ShardingSphere的JDBC URL格式
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yml
    # 这里指定了ShardingSphere的配置文件位置，该文件包含了规则等配置


mybatis:
  mapper-locations: classpath:mybatis/*.xml
#  type-aliases-package: com.czh.pojo
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: /Users/chenzhehao/Documents/work/logAll/${spring.application.name}